# too many tests, hard to diagnose in CI when things fail without using dashboard

name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      # https://github.com/cypress-io/github-action
      - name: Run Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          start: 'npm start'
          wait-on: 'http://localhost:3000'
          config: 'ignoreTestFiles=["spec.js", "**/17-component-testing/*.*"]'
          browser: chrome
          headless: false
