name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      # https://github.com/cypress-io/github-action
      - name: Run Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          config-file: 'cypress-ci.json'
          start: 'npm start'
          wait-on: 'http://localhost:3000'

      # the server is already running, so just test the answers
      - name: Test answers 🤔
        uses: cypress-io/github-action@v2
        with:
          # run every answer spec file, ignore the placeholder files
          config: 'ignoreTestFiles=spec.js'
